#!/usr/bin/env bash
set -euo pipefail

checks=(
  "npm run verify:day0"
  "npm run policy:scan"
  "npm run third-party:check"
  "npm run agent:redact:check"
  "npm run agent:tool:check"
  "npm run agent:mcp-config:check"
  "npm run agent:plugin-policy:check"
  "npm run db:schema:check"
  "npm run public-surface:check"
  "npm run intake:check"
  "npm run external-import:check"
  "npm run external-import:quarantine:check"
  "npm run external-import:seed-dry-run"
  "npm run geo-checker:check"
  "npm run seed-audit:check"
  "npm run report:founder-intent:check"
  "npm run editorial-draft:check"
  "npm run editorial-copy:check"
  "npm run brand-voice:check"
  "npm run scouted-profile:check"
  "npm run conversion-metrics:check"
  "npm run submission-channels:check"
  "npm run founder-onboarding:check"
  "npm run featured-signals:check"
  "npm run ad-payment-boundary:check"
  "npm run lifecycle-archive:check"
  "npm run changelog-engine:check"
  "npm run backers-landing:check"
  "npm run oss-maintainer:check"
  "npm run public-api-boundary:check"
  "npm run public-api:v0:check"
  "npm run mcp-threat-model:check"
  "npm run agent:gate-coverage:check"
  "npm run agent:batch:check"
  "npm run agent:train-plan:check"
  "npm run lint"
  "npm run typecheck"
  "npm run build"
)

for check in "${checks[@]}"; do
  echo "==> ${check}"
  bash -lc "${check}"
done

echo "agent gate passed"
